remote_theme: pmarsceill/just-the-docs
title: Attacks on Implementations Coursebook

gems:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  
webmaster_verifications:
  google: G3nnoOJAuTy9rt3nEkP

plugins:
  - jekyll-seo-tag

